/* 🎯 Challenges — Match the Masterpiece (DECISIONS B32).
   Deliberate practice (Ericsson): clear goal (the ghost) · edge-of-ability effort (blank
   editor) · immediate specific feedback (matched/missing/extra lines). The hidden `code` is
   the target-maker only — matching is by SHAPE + color, never by comparing to this script;
   any code that draws the goal is a win. All original, deterministic, prerequisite-gated
   automatically from the code (same computeGate as the bank). */

const CHALLENGES = [
  { id: "ch01", emoji: "📐", title: "The Corner",
    goal: "Walk 100 steps, turn right, walk 100 more. Two lines, one corner.",
    code: `forward(100)\nright(90)\nforward(100)`,
    hints: ["The turtle starts facing up. forward(100) is your first line.",
            "right(90) turns the corner — then one more forward(100)."] },
  { id: "ch02", emoji: "🇱", title: "The Long L",
    goal: "A tall line of 120, then a short foot of 60 to the right.",
    code: `forward(120)\nright(90)\nforward(60)`,
    hints: ["Same idea as The Corner — but the two walks are different lengths.",
            "120 up, turn right, 60 across."] },
  { id: "ch03", emoji: "🌇", title: "Sunset Dots",
    goal: "A gold dot of size 40 at the start point, and a darkorange dot of size 24 straight above it at height 80.",
    code: `color("gold")\ndot(40)\npenup()\njump(0, 80)\ncolor("darkorange")\ndot(24)`,
    hints: ["dot(40) stamps where the turtle stands. Set the color first.",
            "jump(0, 80) teleports straight up — then the smaller dot."] },
  { id: "ch04", emoji: "🟥", title: "Crimson Corner",
    goal: "The Corner again — but drawn in crimson. (Any pen width you like.)",
    code: `color("crimson")\nforward(100)\nright(90)\nforward(100)`,
    hints: ["color(\"crimson\") before any walking.",
            "Then it's exactly The Corner: 100, right, 100."] },
  { id: "ch05", emoji: "🟦", title: "The Square",
    goal: "A teal square with sides of 120.",
    code: `color("teal")\nfor i in range(4):\n    forward(120)\n    right(90)`,
    hints: ["Four sides, four right(90) turns. A loop makes it four lines of code.",
            "Loop or no loop — the drawing decides, not the method."] },
  { id: "ch06", emoji: "🔺", title: "The Triangle",
    goal: "A seagreen triangle with sides of 140.",
    code: `color("seagreen")\nfor i in range(3):\n    forward(140)\n    right(120)`,
    hints: ["Three sides — but the turn is NOT 90. A triangle folds sharper.",
            "The outside turn of a triangle is 120 degrees."] },
  { id: "ch07", emoji: "⭐", title: "The Star",
    goal: "A gold five-pointed star with sides of 150.",
    code: `color("gold")\nfor i in range(5):\n    forward(150)\n    right(144)`,
    hints: ["You drew this in World 1's finale. Five lines, same turn each time.",
            "The star's secret number is 144."] },
  { id: "ch08", emoji: "💥", title: "The Burst",
    goal: "Twelve crimson rays of 80, out and back, spinning 30 degrees between rays.",
    code: `color("crimson")\nfor i in range(12):\n    forward(80)\n    back(80)\n    right(30)`,
    hints: ["Each ray is forward then back — the turtle returns to the center every time.",
            "12 rays x 30 degrees = the full circle."] },
  { id: "ch09", emoji: "🌀", title: "The Spiral",
    goal: "A purple spiral: 50 laps, each lap walking i × 3, turning 91 after each.",
    code: `color("purple")\nfor i in range(50):\n    forward(i * 3)\n    right(91)`,
    hints: ["The loop counter i must feed the forward — that's what makes it grow.",
            "for i in range(50): then forward(i * 3) and right(91)."] },
  { id: "ch10", emoji: "🔳", title: "Twin Squares",
    goal: "Two darkcyan squares from the same corner: one with sides 60, one with sides 120.",
    code: `color("darkcyan")\nfor i in range(4):\n    forward(60)\n    right(90)\nfor i in range(4):\n    forward(120)\n    right(90)`,
    hints: ["Draw the small square first — the turtle ends where it started, ready for the big one.",
            "Two loops, one after the other. Or one jar used twice, doubled."] },
  { id: "ch11", emoji: "🍯", title: "The Honey Cell",
    goal: "A goldenrod hexagon with sides of 70.",
    code: `color("goldenrod")\nfor i in range(6):\n    forward(70)\n    right(60)`,
    hints: ["Six sides. The turn is gentler than a square's.",
            "Six turns of 60 make the full 360."] },
  { id: "ch12", emoji: "🧭", title: "The Compass",
    goal: "Four steelblue arms of 100 — north, east, south, west — out and back from the center.",
    code: `color("steelblue")\nfor i in range(4):\n    forward(100)\n    back(100)\n    right(90)`,
    hints: ["Like The Burst, but only four arms at right angles.",
            "forward, back, right(90) — four times."] },
];
