/* Barmij Code Bank — batch 1 (DECISIONS B17). Every program authored original for Barmij,
   under docs/CONTENT_POLICY.md. rank: "m" Mustakshif · "b" Bannaa · "r" Ra'id (peek-ahead ok —
   the bank never locks; curiosity is allowed). talks: uses input()/print conversation. */

const CODEBANK = [
  /* ---------- Mustakshif — first art ---------- */
  { id: "cb001", rank: "m", world: 1, emoji: "🟦", title: "First square",
    caption: "Four steps, four turns — the oldest shape in geometry.",
    remix: "Change 120 to 60. Then to 200. Who decides the size? You do.",
    think: [
      "What do I want? A square — four equal sides.",
      "What repeats? Walk, then turn. Four times exactly.",
      "When something repeats, I never copy-paste — I command repetition: <code class=\"k\">for i in range(4):</code>",
      "How much to turn? A square's corner is <code class=\"a\">90</code>°.",
      "Before running, I picture it: walk-turn, walk-turn, walk-turn, walk-turn… closed. Now I check my guess.",
    ],
    code: `color("royalblue")\nwidth(6)\nfor i in range(4):\n    forward(120)\n    right(90)\n` },
  { id: "cb002", rank: "m", world: 1, emoji: "🚦", title: "Traffic light",
    caption: "Three dots, three colors — drawn with jump() and dot().",
    remix: "Make the lights bigger with dot(30). Or build a 4-light alien signal.",
    code: `penup()\njump(0, 90)\ncolor("crimson")\ndot(24)\njump(0, 30)\ncolor("gold")\ndot(24)\njump(0, -30)\ncolor("seagreen")\ndot(24)\n` },
  { id: "cb003", rank: "m", world: 1, emoji: "🪜", title: "Steps to the majlis",
    caption: "A staircase from one repeating step.",
    remix: "More steps: range(9). Taller steps: forward(45).",
    code: `color("chocolate")\nwidth(5)\nfor i in range(6):\n    forward(35)\n    right(90)\n    forward(35)\n    left(90)\n` },
  { id: "cb004", rank: "m", world: 1, emoji: "🍯", title: "Honeycomb cell",
    caption: "Six sides, sixty degrees — the bees knew geometry first.",
    remix: "range(3) with right(120) makes a triangle. range(8) with right(45)?",
    code: `color("goldenrod")\nwidth(6)\nfor i in range(6):\n    forward(70)\n    right(60)\n` },
  { id: "cb005", rank: "m", world: 1, emoji: "⭐", title: "Star of the flag",
    caption: "The five-point star — 144° is its secret number.",
    remix: "color(\"crimson\") for a flag-day star. Or size 220 to fill the sky.",
    code: `color("gold")\nwidth(5)\nfor i in range(5):\n    forward(150)\n    right(144)\n` },
  { id: "cb006", rank: "m", world: 1, emoji: "🏜️", title: "Dashes in the sand",
    caption: "penup() lifts the pen — that's how footprints skip.",
    remix: "Shorter gaps: forward(8) after penup(). A dotted trail?",
    code: `color("peru")\nwidth(6)\nright(90)\nfor i in range(8):\n    pendown()\n    forward(22)\n    penup()\n    forward(14)\n` },
  { id: "cb007", rank: "m", world: 1, emoji: "🔺", title: "Three friends",
    caption: "Three triangles, three colors, standing together.",
    remix: "Give each friend a different size. Or add a fourth friend!",
    code: `width(5)\ncolor("hotpink")\nfor i in range(3):\n    forward(80)\n    right(120)\npenup()\njump(130, 0)\npendown()\ncolor("royalblue")\nfor i in range(3):\n    forward(80)\n    right(120)\npenup()\njump(-130, 0)\npendown()\ncolor("seagreen")\nfor i in range(3):\n    forward(80)\n    right(120)\n` },
  { id: "cb008", rank: "m", world: 1, emoji: "🌅", title: "Sunrise arc",
    caption: "Many tiny steps + tiny turns = a smooth curve.",
    remix: "Tinier turns — left(5) with range(36) — make a rounder sun.",
    code: `color("orange")\nwidth(8)\nright(90)\nfor i in range(18):\n    forward(14)\n    left(10)\n` },
  { id: "cb009", rank: "m", world: 1, emoji: "🪁", title: "Kite over the corniche",
    caption: "A diamond and its string.",
    remix: "Angle the string with right(20) before drawing it.",
    code: `color("mediumorchid")\nwidth(5)\nright(45)\nfor i in range(4):\n    forward(90)\n    right(90)\nright(135)\nwidth(2)\ncolor("gray")\nforward(150)\n` },
  { id: "cb010", rank: "m", world: 1, emoji: "🗣️", title: "Salam, world",
    caption: "The oldest tradition in programming — greeting the world. In both our languages.",
    remix: "Add a third line greeting your city: print(\"Salam, Al Ain!\")",
    code: `print("Salam, world!")\nprint("Hello from the UAE!")\n`, talks: true },

  /* ---------- Bannaa — loops, chance, decisions ---------- */
  { id: "cb011", rank: "b", world: 1, emoji: "🌀", title: "Spiral galaxy",
    caption: "The loop-counter i grows every lap — so every line grows.",
    remix: "right(90) makes a square galaxy. right(121) makes... run it and see.",
    code: `color("purple")\nwidth(3)\nfor i in range(70):\n    forward(i * 3)\n    right(91)\n` },
  { id: "cb012", rank: "b", world: 1, emoji: "🕸️", title: "Star web",
    caption: "36 lines and one stubborn angle weave a web.",
    remix: "Try right(170) → 175 → 160. Each angle is a different universe.",
    code: `color("teal")\nwidth(2)\nfor i in range(36):\n    forward(130)\n    right(170)\n` },
  { id: "cb013", rank: "b", world: 1, emoji: "🕌", title: "Eight-point zellij star",
    caption: "The star you've seen in mosque tiles — right(135), eight times.",
    remix: "width(2) and repeat the loop after right(22) for a layered tile.",
    code: `color("darkcyan")\nwidth(4)\nfor i in range(8):\n    forward(110)\n    right(135)\n` },
  { id: "cb014", rank: "b", world: 2, emoji: "🎆", title: "National Day sky",
    caption: "Random jumps + random colors = a firework show, different every run.",
    remix: "More rockets: range(25). Bigger bursts: dot(random.randint(8, 18)).",
    code: `import random\n\nfor i in range(14):\n    penup()\n    jump(random.randint(-170, 170), random.randint(-120, 130))\n    pendown()\n    color(random.choice(["gold", "crimson", "seagreen", "hotpink", "royalblue"]))\n    dot(random.randint(5, 12))\n` },
  { id: "cb015", rank: "b", world: 1, emoji: "✨", title: "Single burst",
    caption: "forward then back, spinning — one firework, frozen mid-boom.",
    remix: "range(36) with right(10) for a denser boom. Color it your way.",
    code: `color("gold")\nwidth(3)\nfor i in range(24):\n    forward(75)\n    back(75)\n    right(15)\n` },
  { id: "cb016", rank: "b", world: 1, emoji: "🐪", title: "Desert dunes",
    caption: "Curves up, curves down — the road to Liwa.",
    remix: "Make the dunes taller: forward(18). Add a third pair of arcs.",
    code: `color("peru")\nwidth(6)\nright(90)\nfor i in range(12):\n    forward(13)\n    left(7)\nfor i in range(12):\n    forward(13)\n    right(7)\nfor i in range(12):\n    forward(13)\n    left(7)\nfor i in range(12):\n    forward(13)\n    right(7)\n` },
  { id: "cb017", rank: "b", world: 1, emoji: "⛵", title: "Dhow sketch",
    caption: "A hull, a mast, a sail — three strokes of heritage.",
    remix: "A second, smaller dhow on the horizon? jump() is your friend.",
    code: `width(6)\ncolor("saddlebrown")\npenup()\njump(-80, -40)\npendown()\nright(90)\nforward(160)\npenup()\njump(0, -40)\npendown()\nleft(90)\nforward(120)\ncolor("whitesmoke")\nwidth(4)\nright(150)\nforward(105)\nright(105)\nforward(55)\n` },
  { id: "cb018", rank: "b", world: 2, emoji: "🚶", title: "Random walk in the souq",
    caption: "Every turn decided by chance — no two walks alike.",
    remix: "Add 45 and -45 to the choice list for diagonal alleys.",
    code: `import random\n\ncolor("mediumseagreen")\nwidth(4)\nfor i in range(60):\n    forward(16)\n    right(random.choice([0, 90, -90]))\n` },
  { id: "cb019", rank: "b", world: 2, emoji: "🎨", title: "Color wheel of dots",
    caption: "Twelve random-colored dots in a perfect circle.",
    remix: "range(24) with right(15) for a fuller wheel.",
    code: `import random\n\nfor i in range(12):\n    penup()\n    forward(110)\n    color(random.choice(["gold", "orchid", "teal", "crimson", "royalblue", "orange"]))\n    dot(11)\n    back(110)\n    right(30)\n` },
  { id: "cb020", rank: "b", world: 1, emoji: "🌙", title: "Crescent sketch",
    caption: "Two arcs, one moon — the shape we all look for.",
    remix: "Tilt it: right(30) before drawing. A star beside it? You know how.",
    code: `color("gold")\nwidth(5)\nfor i in range(20):\n    forward(16)\n    left(9)\nleft(160)\nfor i in range(20):\n    forward(13)\n    right(7)\n` },
  { id: "cb021", rank: "b", world: 1, emoji: "💓", title: "City heartbeat",
    caption: "A pulse line, like the monitor in a hospital drama.",
    remix: "More beats: copy the middle four lines again.",
    code: `color("hotpink")\nwidth(4)\nright(90)\nforward(60)\nleft(60)\nforward(30)\nright(120)\nforward(30)\nleft(120)\nforward(30)\nright(60)\nforward(60)\n` },
  { id: "cb022", rank: "b", world: 2, emoji: "☕", title: "Karak or gahwa?",
    caption: "Let chance settle the day's most important question.",
    remix: "Add your own drinks to the list — laban? Moroccan tea?",
    code: `import random\n\nprint("The big question: karak or gahwa?")\nprint(random.choice(["Karak — extra sweet", "Gahwa, with dates", "Both. It is Friday."]))\n`, talks: true },
  { id: "cb023", rank: "b", world: 2, emoji: "📅", title: "Days of adventures",
    caption: "Your age, converted into days of living.",
    remix: "Add hours: age * 365 * 24. That's a lot of hours.",
    code: `age = int(input("How old are you?"))\nprint("That is about " + str(age * 365) + " days of adventures!")\nprint("And every single one counted.")\n`, talks: true },
  { id: "cb024", rank: "b", world: 2, emoji: "🎲", title: "Dice duel",
    caption: "You against the computer — two dice, one winner.",
    remix: "Make it best-of-luck with 20-sided dice: randint(1, 20).",
    code: `import random\n\nmine = random.randint(1, 6)\nyours = random.randint(1, 6)\nprint("My die: " + str(mine))\nprint("Your die: " + str(yours))\nif yours > mine:\n    print("You win this round!")\nelif yours < mine:\n    print("The machine takes it - run again!")\nelse:\n    print("A draw! The dice demand a rematch.")\n`, talks: true },
  { id: "cb025", rank: "b", world: 2, emoji: "🤖", title: "The polite robot",
    caption: "It learns your name, then treats you like a guest.",
    remix: "Teach it a second compliment. Or a follow-up question.",
    code: `import random\n\nname = input("Ahlan! What is your name?")\nprint("Welcome to the majlis, " + name + "!")\nprint(random.choice([\n    "Your code style is excellent today, " + name,\n    name + ", the turtle speaks highly of you",\n    "An honor to compute for you, " + name,\n]))\n`, talks: true },
  { id: "cb026", rank: "b", world: 2, emoji: "🚪", title: "Password gate",
    caption: "if == guards the door. Only the right word opens it.",
    remix: "Change the password. Add a second gate behind the first.",
    code: `word = input("Whisper the password...")\nif word == "barmij":\n    print("The majlis door opens. Welcome.")\nelse:\n    print("Hmm... the door stays closed. Try again, friend.")\n`, talks: true },
  { id: "cb027", rank: "b", world: 2, emoji: "✂️", title: "Rock, paper, scissors",
    caption: "The world's fastest game, versus the machine.",
    remix: "Print a taunt when the machine wins. Keep it polite!",
    code: `import random\n\nme = random.choice(["rock", "paper", "scissors"])\nyou = input("rock, paper or scissors?")\nprint("I chose " + me)\nif you == me:\n    print("Draw! Great minds.")\nelif you == "rock" and me == "scissors":\n    print("Your rock crushes my scissors - you win!")\nelif you == "paper" and me == "rock":\n    print("Your paper wraps my rock - you win!")\nelif you == "scissors" and me == "paper":\n    print("Your scissors cut my paper - you win!")\nelse:\n    print("This round is mine - run it back!")\n`, talks: true },
  { id: "cb028", rank: "b", world: 1, emoji: "🌟", title: "Seven-point wonder",
    caption: "Five points was practice. Seven is a flex — angle 154.3.",
    remix: "Nine points? The angle is 140. Eleven? Investigate, mathematician.",
    code: `color("crimson")\nwidth(4)\nfor i in range(7):\n    forward(140)\n    right(154.3)\n` },

  /* ---------- Ra'id — peek-ahead power ---------- */
  { id: "cb029", rank: "r", world: 3, emoji: "🕌", title: "Zellij rosette (nested loops)",
    caption: "A loop inside a loop — six hexagons in a ring. World 3 magic, previewed.",
    remix: "Change both range() numbers. Symmetry lives in their product.",
    code: `color("darkslateblue")\nwidth(3)\nfor i in range(6):\n    for j in range(6):\n        forward(60)\n        right(60)\n    right(60)\n` },
  { id: "cb030", rank: "r", world: 3, emoji: "💫", title: "Growing stars",
    caption: "Five stars, each bigger than the last, sharing one heart.",
    remix: "right(10) between stars twists the stack into a galaxy.",
    code: `color("goldenrod")\nwidth(2)\nfor i in range(5):\n    for j in range(5):\n        forward(40 + i * 25)\n        right(144)\n    right(15)\n` },
  { id: "cb031", rank: "r", world: 3, emoji: "🎰", title: "Mystery art machine",
    caption: "Every parameter random — the machine surprises even its maker.",
    remix: "Restrict the angle list to [90] only. Order from chaos.",
    code: `import random\n\nfor i in range(40):\n    color(random.choice(["teal", "orchid", "gold", "crimson", "royalblue"]))\n    width(random.randint(2, 8))\n    forward(random.randint(20, 90))\n    right(random.choice([60, 90, 120, 144]))\n` },
  { id: "cb032", rank: "r", world: 5, emoji: "🔢", title: "Fibonacci's petals",
    caption: "Each number is the sum of the two before — nature's counting.",
    remix: "How big is the 15th number? Extend the range and find out.",
    code: `a = 1\nb = 1\nfor i in range(10):\n    print(a)\n    nxt = a + b\n    a = b\n    b = nxt\nprint("...and nature uses these in sunflowers.")\n`, talks: true },
  { id: "cb033", rank: "r", world: 3, emoji: "🚀", title: "Countdown to Mars",
    caption: "range can count DOWN too — ask the Hope Probe.",
    remix: "Start from 20. Add a stage-separation message at 5.",
    code: `for i in range(10, 0, -1):\n    print(str(i) + "...")\nprint("LIFT OFF! Next stop: Mars.")\nprint("The Hope Probe sends its regards.")\n`, talks: true },
  { id: "cb034", rank: "r", world: 2, emoji: "🧮", title: "Times-table artist",
    caption: "Pick a table; the machine recites it perfectly, instantly.",
    remix: "Print only the answers. Or make it recite backwards.",
    code: `n = int(input("Which times table? (like 7)"))\nfor i in range(1, 11):\n    print(str(n) + " x " + str(i) + " = " + str(n * i))\nprint("Memorized in 0.001 seconds. Your turn takes longer - and counts more.")\n`, talks: true },
  { id: "cb035", rank: "r", world: 3, emoji: "🌺", title: "Rose window",
    caption: "36 rotated squares — cathedral-window geometry from two loops.",
    remix: "Rotate by 5 instead of 10 for 72 squares. Patience, artist.",
    code: `color("mediumvioletred")\nwidth(1)\nfor i in range(36):\n    for j in range(4):\n        forward(90)\n        right(90)\n    right(10)\n` },
  { id: "cb036", rank: "r", world: 3, emoji: "🐚", title: "Pearl spiral",
    caption: "A tightening spiral, like the shell a pearl diver knows.",
    remix: "right(89.5) — barely different number, completely different shell.",
    code: `color("lightseagreen")\nwidth(2)\nfor i in range(90):\n    forward(i * 2)\n    right(89.5)\n` },
  { id: "cb037", rank: "b", world: 2, emoji: "🦅", title: "Falcon reflex test",
    caption: "The machine picks a number — your instinct hunts it.",
    remix: "Widen the hunt: randint(1, 50). A falcon fears no range.",
    code: `import random\n\nsecret = random.randint(1, 10)\nguess = int(input("The falcon hides a number, 1 to 10. Strike!"))\nif guess == secret:\n    print("Direct hit! It was " + str(secret) + ". Falcon-eyed.")\nelif guess > secret:\n    print("Too high - it was " + str(secret) + ". Dive again!")\nelse:\n    print("Too low - it was " + str(secret) + ". Climb again!")\n`, talks: true },
  { id: "cb038", rank: "m", world: 1, emoji: "🛣️", title: "Desert highway",
    caption: "Two solid lines, one dashed middle — the E11 in four loops.",
    remix: "Make the dashes yellow. Add a fourth lane.",
    code: `width(5)\ncolor("dimgray")\npenup()\njump(-40, -140)\npendown()\nforward(280)\npenup()\njump(40, -140)\npendown()\nforward(280)\ncolor("gold")\nwidth(3)\npenup()\njump(0, -140)\npendown()\nfor i in range(7):\n    forward(24)\n    penup()\n    forward(16)\n    pendown()\n` },
  { id: "cb039", rank: "b", world: 1, emoji: "🎡", title: "Ain Dubai",
    caption: "A wheel of spokes — 18 lines from one center.",
    remix: "36 spokes with right(10). Add a dot() at each tip.",
    code: `color("steelblue")\nwidth(3)\nfor i in range(18):\n    forward(120)\n    back(120)\n    right(20)\n` },
  { id: "cb040", rank: "r", world: 3, emoji: "❄️", title: "Impossible snowflake",
    caption: "Six arms, each with tiny branches — in the desert, we code our snow.",
    remix: "Eight arms: range(8) and right(45). A different crystal entirely.",
    code: `color("skyblue")\nwidth(3)\nfor i in range(6):\n    forward(100)\n    for j in range(3):\n        forward(30)\n        back(30)\n        right(45)\n    right(45)\n    back(100)\n    right(60)\n` },

  /* ========== batch 2 (2026-09-14) — blueprint-targeted: decision cluster, loop-var
     reinforcement, randint, spirals/interleaving, Mustakshif floor. BANK_BLUEPRINT.md ========== */

  /* ---- loop-variable reinforcement ---- */
  { id: "cb041", rank: "m", world: 1, emoji: "📶", title: "Growing steps",
    caption: "The loop counter i makes each line longer than the last.",
    remix: "Change i * 12 to i * 20. Giant steps!",
    code: `color("royalblue")\nwidth(5)\nfor i in range(6):\n    forward(i * 12)\n    right(90)\n` },
  { id: "cb042", rank: "m", world: 1, emoji: "🪭", title: "Paper fan",
    caption: "Each rib grows with i — open the fan.",
    remix: "right(20) closes the fan tighter. right(45) opens it wide.",
    code: `color("teal")\nwidth(4)\nfor i in range(7):\n    forward(50 + i * 15)\n    back(50 + i * 15)\n    right(30)\n` },
  { id: "cb043", rank: "b", world: 1, emoji: "🖌️", title: "Thickening rays",
    caption: "This time i controls the pen WIDTH, not the length.",
    remix: "Swap: fixed width, growing length. Which looks better?",
    code: `color("crimson")\nfor i in range(9):\n    width(i + 1)\n    forward(100)\n    back(100)\n    right(15)\n` },
  { id: "cb044", rank: "b", world: 1, emoji: "🌪️", title: "Square whirlpool",
    caption: "A square spiral — i stretches every side.",
    remix: "right(89) instead of 90 — the whirlpool starts to lean.",
    think: [
      "I want a spiral — a shape that GROWS as it turns.",
      "Growth means: each line a little longer than the one before.",
      "Who counts for me? The loop already does — <code class=\"v\">i</code> goes 0, 1, 2, 3…",
      "So the length should USE the counter: <code class=\"k\">forward</code>(<code class=\"v\">i</code> * <code class=\"a\">3</code>).",
      "Keep the turn at 90 and the square twists outward. My prediction: a whirlpool. Run and check me.",
    ],
    code: `color("darkcyan")\nwidth(3)\nfor i in range(40):\n    forward(i * 3)\n    right(90)\n` },
  { id: "cb045", rank: "b", world: 1, emoji: "☄️", title: "Comet tail",
    caption: "The dots shrink as i grows: 12 - i.",
    remix: "Make the comet longer: range(12) and start dot(14).",
    code: `color("goldenrod")\nfor i in range(10):\n    penup()\n    forward(26)\n    dot(12 - i)\n` },
  { id: "cb046", rank: "r", world: 1, emoji: "🌌", title: "Galaxy arms",
    caption: "i * 2 and a stubborn 58° — spiral arms of a tiny galaxy.",
    remix: "Angles 59, 60, 61 — three completely different galaxies.",
    code: `color("mediumorchid")\nwidth(2)\nfor i in range(85):\n    forward(i * 2)\n    right(58)\n` },
  { id: "cb047", rank: "m", world: 1, emoji: "🔟", title: "Counting turtle",
    caption: "print can use i too — the loop counts out loud.",
    remix: "Count higher: range(10). What number does it START from?",
    code: `for i in range(5):\n    print("Step number " + str(i))\nprint("The count starts at ZERO - a programmer's secret.")\n`, talks: true },
  { id: "cb048", rank: "b", world: 1, emoji: "🕐", title: "Numbered clock",
    caption: "Twelve dots in a circle — and i labels each hour.",
    remix: "Make it a 24-hour clock: range(24), right(15).",
    code: `color("steelblue")\nfor i in range(12):\n    penup()\n    forward(105)\n    dot(7)\n    back(105)\n    right(30)\n    print("hour " + str(i + 1))\n`, talks: true },
  { id: "cb049", rank: "r", world: 1, emoji: "🌙", title: "Staircase to the moon",
    caption: "Growing steps at 45° — climb.",
    remix: "range(20) climbs beyond the canvas. Where does the turtle go?",
    code: `color("slateblue")\nwidth(4)\nfor i in range(14):\n    forward(i * 4)\n    right(45)\n` },
  { id: "cb050", rank: "b", world: 1, emoji: "🌸", title: "Counted petals",
    caption: "Six petals drawn AND announced — art that narrates itself.",
    remix: "Eight petals: range(8) and right(45).",
    code: `color("hotpink")\nwidth(5)\nfor i in range(6):\n    forward(85)\n    back(85)\n    right(60)\n    print("petal " + str(i + 1) + " done")\n`, talks: true },

  /* ---- the decision cluster: if / elif / comparisons ---- */
  { id: "cb051", rank: "m", world: 2, emoji: "⚖️", title: "Big or small?",
    caption: "Your first comparison: is the number bigger than 10?",
    remix: "Change 10 to 100. Now what counts as big?",
    code: `n = int(input("Give me any number..."))\nif n > 10:\n    print(str(n) + " is BIG!")\nelse:\n    print(str(n) + " is small and lovely.")\n`, talks: true },
  { id: "cb052", rank: "m", world: 2, emoji: "🌞", title: "Sun or moon",
    caption: "Your answer decides what appears in the sky.",
    remix: "Add a third choice with elif: \"star\" draws a tiny gold dot.",
    code: `answer = input("Sun or moon?")\nif answer == "sun":\n    color("gold")\n    dot(60)\nelse:\n    color("lightsteelblue")\n    dot(45)\n`, talks: true },
  { id: "cb053", rank: "b", world: 2, emoji: "🎨", title: "Warm or cool",
    caption: "One question paints the whole square.",
    remix: "Warm could be \"crimson\"… or random.choice of three warm colors!",
    code: `feel = input("Warm colors or cool colors?")\nif feel == "warm":\n    color("darkorange")\nelse:\n    color("royalblue")\nwidth(9)\nfor i in range(4):\n    forward(110)\n    right(90)\n`, talks: true },
  { id: "cb054", rank: "b", world: 2, emoji: "💪", title: "The encourager",
    caption: "An elif ladder that ALWAYS finds something kind to say.",
    remix: "Add a 50-69 rung with its own message.",
    think: [
      "Goal: a different reply for different scores. 'Different for different' smells like a decision.",
      "More than two roads? That's a ladder: <code class=\"k\">if</code>, then <code class=\"k\">elif</code>, then <code class=\"k\">else</code>.",
      "Python checks from the TOP down and takes the FIRST true road — so I put the biggest test first: >= 90.",
      "If I tested >= 70 first, a 95 would stop there. Order is part of the logic — I always check my order.",
      "<code class=\"k\">else</code> catches everyone left — and I make sure even that road is kind. Run.",
    ],
    code: `score = int(input("Your quiz score, 0 to 100?"))\nif score >= 90:\n    print("Mumtaz! Top of the class energy.")\nelif score >= 70:\n    print("Strong! A little polish and it is gold.")\nelse:\n    print("Every master started here. Go again - I believe in you.")\n`, talks: true },
  { id: "cb055", rank: "b", world: 2, emoji: "🔢", title: "Which is bigger?",
    caption: "Two numbers walk in. The machine judges instantly.",
    remix: "Three numbers? You'll need a cleverer ladder…",
    code: `a = int(input("First number?"))\nb = int(input("Second number?"))\nif a > b:\n    print(str(a) + " wins!")\nelif b > a:\n    print(str(b) + " wins!")\nelse:\n    print("A perfect tie!")\n`, talks: true },
  { id: "cb056", rank: "b", world: 2, emoji: "🚦", title: "Traffic judge",
    caption: "Type a light color — the machine obeys the road rules.",
    remix: "Add \"yellow\" with elif — and its own careful message.",
    code: `light = input("The light is red or green?")\nif light == "red":\n    color("crimson")\n    dot(40)\n    print("STOP - habibi, patience.")\nelif light == "green":\n    color("seagreen")\n    dot(40)\n    print("Yalla, go!")\nelse:\n    print("That light does not exist in Abu Dhabi.")\n`, talks: true },
  { id: "cb057", rank: "b", world: 2, emoji: "🎢", title: "The ride gate",
    caption: "Compare a number to a rule — like the sign at the theme park.",
    remix: "Make a VIP gate too: another if with >= 16.",
    code: `age = int(input("How old are you?"))\nif age >= 12:\n    print("Welcome to the BIG rollercoaster!")\nelse:\n    print("The kart track is calling you - it is honestly more fun.")\n`, talks: true },
  { id: "cb058", rank: "r", world: 2, emoji: "🦅", title: "Falcon wind check",
    caption: "Three ranges, three flying decisions — a real elif ladder.",
    remix: "Add a fourth rung: over 60 means sandstorm, stay home.",
    code: `wind = int(input("Wind speed in km/h?"))\nif wind > 40:\n    print("Too strong - the falcon waits on the glove.")\nelif wind > 20:\n    print("Good hunting wind. She flies!")\nelse:\n    print("Calm skies - perfect for training.")\n`, talks: true },
  { id: "cb059", rank: "m", world: 2, emoji: "🌷", title: "Yes-no flower",
    caption: "Say yes and the flower blooms pink. Anything else — blue.",
    remix: "Swap the colors. Or make \"no\" draw a single dot.",
    code: `answer = input("Do you like flowers? yes or no")\nif answer == "yes":\n    color("hotpink")\nelse:\n    color("royalblue")\nwidth(5)\nfor i in range(8):\n    forward(70)\n    back(70)\n    right(45)\n`, talks: true },
  { id: "cb060", rank: "b", world: 2, emoji: "🌡️", title: "What to wear (UAE edition)",
    caption: "An elif ladder for our weather — 25° counts as winter here.",
    remix: "Add the rare rung: under 15 means jacket AND celebration.",
    code: `temp = int(input("Temperature today, in C?"))\nif temp >= 40:\n    print("Full summer mode: stay near the AC, hero.")\nelif temp >= 25:\n    print("A beautiful normal day.")\nelse:\n    print("WINTER! Everyone to the desert for camping!")\n`, talks: true },
  { id: "cb061", rank: "b", world: 2, emoji: "🔤", title: "Secret shape letter",
    caption: "One letter chooses the geometry.",
    remix: "Add \"p\" for a pentagon: range(5), right(72).",
    code: `letter = input("Type s for square, t for triangle...")\ncolor("darkcyan")\nwidth(6)\nif letter == "s":\n    for i in range(4):\n        forward(100)\n        right(90)\nelif letter == "t":\n    for i in range(3):\n        forward(100)\n        right(120)\nelse:\n    dot(30)\n`, talks: true },
  { id: "cb062", rank: "r", world: 2, emoji: "🌀", title: "Spiral flavor picker",
    caption: "Your number picks the spiral's soul: 1, 2 or 3.",
    remix: "Add flavor 4 with your own secret angle.",
    code: `flavor = int(input("Pick a spiral: 1, 2 or 3"))\ncolor("purple")\nwidth(3)\nif flavor == 1:\n    angle = 91\nelif flavor == 2:\n    angle = 121\nelse:\n    angle = 144\nfor i in range(60):\n    forward(i * 3)\n    right(angle)\n`, talks: true },
  { id: "cb063", rank: "b", world: 2, emoji: "☕", title: "Karak sugar meter",
    caption: "The machine keeps an eye on your sugar spoons.",
    remix: "Add a zero-spoons rung: \"respect, ya captain.\"",
    code: `spoons = int(input("Spoons of sugar in your karak?"))\nif spoons > 3:\n    print("Ya doctor! Maybe ease off a little :)")\nelse:\n    print("Balanced. The karak approves.")\n`, talks: true },
  { id: "cb064", rank: "b", world: 2, emoji: "👋", title: "Name twin detector",
    caption: "== checks words too — exactly, letter by letter.",
    remix: "Make it greet YOUR name specially instead.",
    code: `name = input("What is your name?")\nif name == "Barmij":\n    print("No way - that is MY name!")\nelse:\n    print("Ahlan, " + name + "! A pleasure to compute for you.")\n`, talks: true },

  /* ---- randint reinforcement ---- */
  { id: "cb065", rank: "m", world: 2, emoji: "🎯", title: "Lucky dot",
    caption: "The dice picks the size — announced, then drawn.",
    remix: "randint(5, 120) — from tiny seed to giant moon.",
    code: `import random\n\nsize = random.randint(10, 45)\nprint("Today's lucky size: " + str(size))\ncolor("gold")\ndot(size)\n`, talks: true },
  { id: "cb066", rank: "b", world: 2, emoji: "🪜", title: "Random staircase",
    caption: "The dice decides how many steps you climb.",
    remix: "Random step SIZE too: forward(random.randint(20, 40)).",
    think: [
      "I want surprise — a different staircase every run.",
      "Surprise means a number I refuse to choose myself: <code class=\"v\">random</code>.<code class=\"k\">randint</code>(<code class=\"a\">3</code>, <code class=\"a\">9</code>).",
      "I store it in a jar — <code class=\"v\">steps</code> — because I'll need it twice: to announce, and to loop.",
      "The loop doesn't care WHERE the number came from. range(steps) just obeys the jar.",
      "One run is one staircase. To trust randomness, I run at least three times. Go.",
    ],
    code: `import random\n\nsteps = random.randint(3, 9)\nprint(str(steps) + " steps today!")\ncolor("chocolate")\nwidth(5)\nfor i in range(steps):\n    forward(30)\n    right(90)\n    forward(30)\n    left(90)\n`, talks: true },
  { id: "cb067", rank: "b", world: 2, emoji: "🧱", title: "Dice tower",
    caption: "Roll a die — build a tower that tall.",
    remix: "Two dice: randint(1,6) + randint(1,6). Skyscraper chances!",
    code: `import random\n\nfloors = random.randint(1, 6)\nprint("Building " + str(floors) + " floors...")\ncolor("peru")\nwidth(4)\nfor i in range(floors):\n    forward(34)\n    right(90)\n    forward(34)\n    right(90)\n    forward(34)\n    right(90)\n    forward(34)\n    right(90)\n    forward(34)\n` },
  { id: "cb068", rank: "b", world: 2, emoji: "🌫️", title: "Sandstorm",
    caption: "Fifteen dots, random places, random sizes — shamal weather.",
    remix: "Make it a golden storm: one fixed color, wilder sizes.",
    code: `import random\n\nfor i in range(15):\n    penup()\n    jump(random.randint(-160, 160), random.randint(-110, 110))\n    color(random.choice(["tan", "peru", "burlywood", "sandybrown"]))\n    dot(random.randint(3, 14))\n` },
  { id: "cb069", rank: "r", world: 2, emoji: "✨", title: "Star of chance",
    caption: "The dice picks 5-point or 7-point — the angle must follow.",
    remix: "Add 9 points to the game: its angle is 140.",
    code: `import random\n\npoints = random.choice([5, 7])\nprint(str(points) + "-pointed star coming up!")\ncolor("crimson")\nwidth(4)\nif points == 5:\n    angle = 144\nelse:\n    angle = 154.3\nfor i in range(points):\n    forward(130)\n    right(angle)\n`, talks: true },
  { id: "cb070", rank: "m", world: 2, emoji: "🪙", title: "Coin flip",
    caption: "randint(0, 1) — the world's smallest dice.",
    remix: "Best of three: run it three times, keep score on paper.",
    code: `import random\n\ncoin = random.randint(0, 1)\nif coin == 0:\n    print("HEADS!")\nelse:\n    print("TAILS!")\n`, talks: true },
  { id: "cb071", rank: "b", world: 2, emoji: "🐾", title: "Wander of chance",
    caption: "Even the LENGTH of the walk is up to the dice.",
    remix: "Diagonal alleys: add 45 and -45 to the choices.",
    code: `import random\n\nsteps = random.randint(25, 60)\nprint("Walking " + str(steps) + " steps...")\ncolor("mediumseagreen")\nwidth(4)\nfor i in range(steps):\n    forward(13)\n    right(random.choice([0, 90, -90]))\n`, talks: true },
  { id: "cb072", rank: "b", world: 2, emoji: "🎁", title: "Mystery gift",
    caption: "A present whose size nobody knows — until you run.",
    remix: "Random ribbon color too, with random.choice.",
    code: `import random\n\nw = random.randint(40, 120)\nh = random.randint(40, 120)\ncolor("mediumvioletred")\nwidth(5)\nfor i in range(2):\n    forward(h)\n    right(90)\n    forward(w)\n    right(90)\n` },

  /* ---- spiral / interleaved: old skills stay warm (blueprint: interleaving) ---- */
  { id: "cb073", rank: "b", world: 2, emoji: "💌", title: "Greeting card machine",
    caption: "input + loops + pen style — three worlds of skill, one card.",
    remix: "Let them choose the frame color too — a second input.",
    think: [
      "Goal: a card — a golden frame, with THEIR name inside the message.",
      "Two jobs: ask the name, draw the frame. I break big goals into small jobs — always.",
      "The name I cannot know in advance. So the program must ask: <code class=\"k\">input</code>().",
      "The frame is a square — I already own that skill. Old skills are bricks; I reuse them.",
      "The message glues my words to theirs: quotes + <b>+</b> + jar. Run — and read the card.",
    ],
    code: `name = input("Who is this card for?")\ncolor("goldenrod")\nwidth(6)\nfor i in range(4):\n    forward(150)\n    right(90)\nprint("To " + name + ": Eid Mubarak from all of us!")\n`, talks: true },
  { id: "cb074", rank: "b", world: 2, emoji: "🕯️", title: "Birthday candles",
    caption: "Your age becomes the drawing — one candle per year.",
    remix: "Tiny flames: a gold dot(5) at the top of each candle.",
    code: `age = int(input("How old are you?"))\ncolor("orchid")\nwidth(4)\nright(90)\nfor i in range(age):\n    left(90)\n    forward(50)\n    back(50)\n    right(90)\n    penup()\n    forward(18)\n    pendown()\n`, talks: true },
  { id: "cb075", rank: "b", world: 2, emoji: "⭐", title: "Star salary",
    caption: "Score in, that many star-rays out — numbers become art.",
    remix: "Gold rays for 8+, silver below — add an if.",
    code: `stars = int(input("How many stars did you earn today?"))\ncolor("gold")\nwidth(4)\nfor i in range(stars):\n    forward(90)\n    back(90)\n    right(30)\nprint(str(stars) + " rays of glory!")\n`, talks: true },
  { id: "cb076", rank: "b", world: 2, emoji: "📣", title: "The echo machine",
    caption: "One name in — a loop of louder and louder echoes out.",
    remix: "Five echoes, and the last one in CAPITALS you type yourself.",
    code: `name = input("Your name, hero?")\nprint(name + "!")\nprint(name + "!!")\nprint(name + "!!!")\nprint("...the mountains echo you, " + name + ".")\n`, talks: true },
  { id: "cb077", rank: "b", world: 2, emoji: "🎭", title: "Robot mood dice",
    caption: "The robot rolls its own mood — then paints it.",
    remix: "Add a fourth mood with its own color and message.",
    code: `import random\n\nmood = random.randint(1, 3)\nif mood == 1:\n    print("The robot is joyful today!")\n    color("gold")\nelif mood == 2:\n    print("The robot is calm and thoughtful.")\n    color("royalblue")\nelse:\n    print("The robot is full of energy!")\n    color("hotpink")\nwidth(6)\nfor i in range(12):\n    forward(70)\n    back(70)\n    right(30)\n`, talks: true },
  { id: "cb078", rank: "r", world: 2, emoji: "🖋️", title: "Lucky-number spiral",
    caption: "Your number sets the galaxy's angle. Every child, a different sky.",
    remix: "Also let it set the color: if, elif, else.",
    code: `lucky = int(input("Your lucky number, 1 to 100?"))\ncolor("darkslateblue")\nwidth(2)\nfor i in range(70):\n    forward(i * 2)\n    right(90 + lucky)\n`, talks: true },
  { id: "cb079", rank: "b", world: 2, emoji: "🔳", title: "Twin squares",
    caption: "One jar, two squares — the second is exactly double.",
    remix: "A third square, triple size. One jar still rules them all.",
    code: `size = int(input("Size of the small square? (try 40)"))\ncolor("teal")\nwidth(4)\nfor i in range(4):\n    forward(size)\n    right(90)\nfor i in range(4):\n    forward(size * 2)\n    right(90)\n`, talks: true },
  { id: "cb080", rank: "b", world: 2, emoji: "⛅", title: "Weather artist",
    caption: "Tell it the sky — it paints the day.",
    remix: "Add \"cloudy\": gray dots scattered with jump.",
    code: `sky = input("Is it sunny or rainy?")\nif sky == "sunny":\n    color("gold")\n    width(5)\n    for i in range(12):\n        forward(80)\n        back(80)\n        right(30)\nelse:\n    color("steelblue")\n    width(3)\n    right(180)\n    for i in range(8):\n        pendown()\n        forward(25)\n        penup()\n        jump(-140 + i * 35, 60)\n`, talks: true },
  { id: "cb081", rank: "m", world: 1, emoji: "🗺️", title: "Hello from four corners",
    caption: "jump to each corner, leave a dot and a greeting.",
    remix: "Different color per corner — four color lines.",
    code: `color("crimson")\npenup()\njump(-120, 90)\ndot(12)\nprint("Salam from the north-west!")\njump(120, 90)\ndot(12)\nprint("Marhaba from the north-east!")\njump(120, -90)\ndot(12)\nprint("Ahlan from the south-east!")\njump(-120, -90)\ndot(12)\nprint("Hala from the south-west!")\n`, talks: true },
  { id: "cb082", rank: "r", world: 3, emoji: "2️⃣", title: "Counting by twos",
    caption: "range has a third number — the STEP. A World 3 secret, early.",
    remix: "Count by fives to 100. Or backwards: range(20, 0, -2).",
    code: `print("Counting by twos:")\nfor i in range(2, 21, 2):\n    print(i)\nprint("Even numbers - collected in one loop.")\n`, talks: true },
  { id: "cb083", rank: "r", world: 3, emoji: "⏳", title: "The patient while",
    caption: "while repeats UNTIL a rule breaks. The counter keeps it honest.",
    remix: "Change n < 5 to n < 8 — three more petals of patience.",
    code: `n = 0\ncolor("seagreen")\nwidth(5)\nwhile n < 5:\n    forward(80)\n    right(72)\n    n = n + 1\nprint("The while stopped itself after " + str(n) + " rounds.")\n`, talks: true },
  { id: "cb084", rank: "r", world: 3, emoji: "🚀", title: "While-powered countdown",
    caption: "You choose where the countdown starts — while does the rest.",
    remix: "Make it count down by 2: n = n - 2.",
    code: `n = int(input("Start the countdown from? (3 to 9)"))\nwhile n > 0:\n    print(str(n) + "...")\n    n = n - 1\nprint("LIFT OFF!")\n`, talks: true },

  /* ---- Mustakshif floor: gentle worked examples ---- */
  { id: "cb085", rank: "m", world: 1, emoji: "🏺", title: "My first jar",
    caption: "One jar called size — used twice. Change it ONCE.",
    remix: "size = 150. Both lines obey. That's the power.",
    think: [
      "I want two lines exactly the same length.",
      "Same value, used twice? I refuse to write 80 twice — numbers repeated by hand drift apart one day.",
      "So: one jar — <code class=\"v\">size</code> = <code class=\"a\">80</code> — and both lines READ the jar.",
      "Now changing my mind costs ONE edit. That is the real reason programmers love variables.",
      "Run it — then change the jar once and feel the power.",
    ],
    code: `size = 80\ncolor("royalblue")\nwidth(6)\nforward(size)\nright(90)\nforward(size)\n` },
  { id: "cb086", rank: "m", world: 1, emoji: "🏺", title: "Two jars",
    caption: "Jars can hold different things — tall and wide.",
    remix: "Make wide bigger than tall. A sleeping rectangle!",
    code: `tall = 120\nwide = 60\ncolor("darkcyan")\nwidth(5)\nfor i in range(2):\n    forward(tall)\n    right(90)\n    forward(wide)\n    right(90)\n` },
  { id: "cb087", rank: "m", world: 1, emoji: "🐾", title: "Dot trail",
    caption: "penup + jump + dot — footprints across the sand.",
    remix: "Make the trail curve: change the y numbers.",
    code: `color("peru")\npenup()\njump(-140, -20)\ndot(9)\njump(-70, 10)\ndot(9)\njump(0, -20)\ndot(9)\njump(70, 10)\ndot(9)\njump(140, -20)\ndot(9)\n` },
  { id: "cb088", rank: "m", world: 1, emoji: "🚩", title: "Tiny flag",
    caption: "A pole and a flag — five lines of code.",
    remix: "Color the flag crimson. Or fly TWO flags with jump.",
    code: `color("dimgray")\nwidth(5)\nforward(140)\ncolor("seagreen")\nwidth(8)\nright(90)\nforward(60)\nright(90)\nforward(25)\nright(90)\nforward(60)\n` },
  { id: "cb089", rank: "b", world: 1, emoji: "🖼️", title: "Frame in a frame",
    caption: "The same square code twice — the jar shrinks between them.",
    remix: "Three frames: shrink the jar once more.",
    code: `size = 140\ncolor("saddlebrown")\nwidth(6)\nfor i in range(4):\n    forward(size)\n    right(90)\npenup()\njump(25, -25)\npendown()\nsize = 90\ncolor("goldenrod")\nfor i in range(4):\n    forward(size)\n    right(90)\n` },
  { id: "cb090", rank: "b", world: 2, emoji: "📿", title: "Misbaha of colors",
    caption: "A circle of beads, each color drawn by chance.",
    remix: "33 beads: range(33) and right(10.9) — the real count.",
    code: `import random\n\nfor i in range(18):\n    penup()\n    forward(100)\n    color(random.choice(["darkcyan", "goldenrod", "sienna", "seagreen"]))\n    dot(9)\n    back(100)\n    right(20)\n` },
  { id: "cb091", rank: "m", world: 1, emoji: "😊", title: "Three happy lines",
    caption: "print three times — the simplest program that smiles.",
    remix: "Make it five lines. Make one of them Arabic.",
    code: `print("Today is a good day.")\nprint("I am learning Python.")\nprint("And Python is learning me!")\n`, talks: true },
  { id: "cb092", rank: "m", world: 1, emoji: "🕌", title: "Salam stack",
    caption: "Greetings of the world, stacked in print.",
    remix: "Add greetings you know — French? Tagalog? Urdu?",
    code: `print("Salam!")\nprint("Marhaba!")\nprint("Hello!")\nprint("Namaste!")\nprint("Ni hao!")\nprint("One world, many greetings, one print.")\n`, talks: true },
  { id: "cb093", rank: "b", world: 1, emoji: "🌳", title: "Ghaf tree sketch",
    caption: "The national tree — a trunk and a crown of rays.",
    remix: "A wider crown: range(9) with right(20) between rays.",
    code: `color("saddlebrown")\nwidth(8)\nforward(90)\ncolor("olivedrab")\nwidth(4)\nleft(60)\nfor i in range(7):\n    forward(55)\n    back(55)\n    right(20)\n` },
  { id: "cb094", rank: "b", world: 1, emoji: "🙂", title: "Smile of dots",
    caption: "A curve of dots — geometry that grins back.",
    remix: "Two eye-dots above it, dot(14) each. A whole face!",
    code: `color("darkorange")\npenup()\njump(-90, 20)\nright(135)\nfor i in range(7):\n    forward(32)\n    dot(10)\n    left(15)\n` },
  { id: "cb095", rank: "r", world: 3, emoji: "🏵️", title: "Hexagon garden",
    caption: "Six hexagons in a ring — nested loops, World 3's signature.",
    remix: "Pentagon garden: both range(5), turns 72.",
    code: `color("darkslateblue")\nwidth(2)\nfor i in range(6):\n    for j in range(6):\n        forward(52)\n        right(60)\n    right(60)\n` },
  { id: "cb096", rank: "b", world: 2, emoji: "🌟", title: "A star with your name on it",
    caption: "The oldest promise, kept by code.",
    remix: "Let them pick the star color with a second input.",
    code: `name = input("Your name, star owner?")\ncolor("gold")\nwidth(5)\nfor i in range(5):\n    forward(140)\n    right(144)\nprint("This star is officially registered to " + name + ".")\n`, talks: true },
  { id: "cb097", rank: "m", world: 1, emoji: "🌅", title: "Warm sun",
    caption: "Twelve golden rays from one center.",
    remix: "A cooler sun? Try \"lightsalmon\" or even \"orchid\".",
    code: `color("gold")\nwidth(6)\nfor i in range(12):\n    forward(85)\n    back(85)\n    right(30)\n` },
  { id: "cb098", rank: "b", world: 1, emoji: "🌴", title: "Palm grove",
    caption: "Three palms planted by one loop — i moves the ground.",
    remix: "Five palms: range(5), and start at -200.",
    code: `for i in range(3):\n    penup()\n    jump(-130 + i * 130, -90)\n    pendown()\n    color("saddlebrown")\n    width(6)\n    forward(70)\n    color("seagreen")\n    width(4)\n    left(50)\n    forward(40)\n    back(40)\n    right(100)\n    forward(40)\n    back(40)\n    left(50)\n    back(70)\n` },
  { id: "cb099", rank: "r", world: 2, emoji: "🕌", title: "Zellij of chance",
    caption: "The dice picks the sacred angle — three tiles live in one code.",
    remix: "Add 160 to the choices. A tile no mosque has seen yet.",
    code: `import random\n\nangle = random.choice([135, 144, 154.3])\nprint("Today's tile angle: " + str(angle))\ncolor("darkcyan")\nwidth(3)\nfor i in range(16):\n    forward(110)\n    right(angle)\n`, talks: true },
  { id: "cb100", rank: "b", world: 2, emoji: "🎆", title: "Finale: fireworks with your name",
    caption: "Item one hundred — input, loops, chance and color, celebrating YOU.",
    remix: "More rockets: range(20). This is your show now.",
    code: `import random\n\nname = input("Whose celebration is this?")\nfor i in range(12):\n    penup()\n    jump(random.randint(-160, 160), random.randint(-100, 130))\n    color(random.choice(["gold", "crimson", "hotpink", "royalblue", "seagreen"]))\n    dot(random.randint(5, 13))\nprint("Mabrook, " + name + " - one hundred programs strong!")\n`, talks: true },

  /* ========== World 3 batch (2026-09-14): step-range, while, nested ladders ========== */
  { id: "cb106", rank: "b", world: 3, emoji: "3️⃣", title: "Countdown by threes",
    caption: "range(21, 0, -3) — counting down, skipping as it goes.",
    remix: "By sevens from 70. Or by ones — the classic rocket countdown.",
    code: `for n in range(21, 0, -3):\n    print(n)\nprint("Landed. Counting is yours now.")\n`, talks: true },
  { id: "cb107", rank: "b", world: 3, emoji: "🚧", title: "The even fence",
    caption: "Fence posts every 40 steps — range walking through SPACE.",
    remix: "A tighter fence: every 25. A longer one: stop at 200.",
    code: `color("saddlebrown")\nwidth(5)\nfor x in range(-120, 121, 40):\n    penup()\n    jump(x, -60)\n    pendown()\n    forward(80)\n` },
  { id: "cb108", rank: "b", world: 3, emoji: "🪆", title: "Shrinking squares",
    caption: "range counts DOWN — each square smaller than the last.",
    remix: "Shrink by 15 instead of 25. How many squares fit now?",
    code: `color("teal")\nwidth(2)\nfor size in range(120, 19, -25):\n    for j in range(4):\n        forward(size)\n        right(90)\n` },
  { id: "cb109", rank: "r", world: 3, emoji: "🎯", title: "Odd ones only",
    caption: "Start at 1, step by 2 — the odd numbers assemble.",
    remix: "Their sum is always a perfect square. Count and check!",
    code: `print("The odd parade:")\nfor n in range(1, 20, 2):\n    print(n)\n`, talks: true },
  { id: "cb110", rank: "b", world: 3, emoji: "📏", title: "The dot ruler",
    caption: "A dot every 30 steps — measurement, drawn.",
    remix: "Number the marks: print(x) inside the loop.",
    code: `color("steelblue")\nfor x in range(-120, 121, 30):\n    penup()\n    jump(x, 0)\n    dot(6)\n` },
  { id: "cb111", rank: "b", world: 3, emoji: "🌼", title: "Six-petal promise",
    caption: "A while loop that keeps its word: n grows, so it ends.",
    remix: "Nine petals: n < 9 and right(40).",
    code: `color("hotpink")\nwidth(5)\nn = 0\nwhile n < 6:\n    forward(85)\n    back(85)\n    right(60)\n    n = n + 1\n` },
  { id: "cb112", rank: "b", world: 3, emoji: "🪜", title: "While-built staircase",
    caption: "The same staircase — but while holds the count.",
    remix: "Climb to 8. What must change? Only the promise's number.",
    code: `color("chocolate")\nwidth(5)\nn = 0\nwhile n < 5:\n    forward(34)\n    right(90)\n    forward(34)\n    left(90)\n    n = n + 1\n` },
  { id: "cb113", rank: "r", world: 3, emoji: "🐚", title: "The inward spiral",
    caption: "while size > 5 — the loop runs until the spiral runs out.",
    remix: "Shrink by 4 instead of 7 — a tighter, longer shell.",
    code: `color("lightseagreen")\nwidth(3)\nsize = 130\nwhile size > 5:\n    forward(size)\n    right(90)\n    size = size - 7\n` },
  { id: "cb114", rank: "b", world: 3, emoji: "📢", title: "While countdown speaker",
    caption: "while announces every number on the way down.",
    remix: "Count down by 2. Or start from your age.",
    code: `n = 6\nwhile n > 0:\n    print(str(n) + "...")\n    n = n - 1\nprint("Yalla!")\n`, talks: true },
  { id: "cb115", rank: "r", world: 3, emoji: "🔵", title: "Patience dots",
    caption: "Each lap adds a dot — while n counts them all.",
    remix: "Make the dots GROW with n: dot(4 + n).",
    code: `color("mediumorchid")\nn = 0\nwhile n < 10:\n    penup()\n    forward(26)\n    dot(7)\n    n = n + 1\n` },
  { id: "cb116", rank: "b", world: 3, emoji: "🔻", title: "Triangle rosette",
    caption: "Six triangles in rotation — the simplest zellij.",
    remix: "Eight triangles: outer range(8), final right(45).",
    code: `color("crimson")\nwidth(2)\nfor i in range(6):\n    for j in range(3):\n        forward(90)\n        right(120)\n    right(60)\n` },
  { id: "cb117", rank: "b", world: 3, emoji: "🔳", title: "The nine windows",
    caption: "A 3×3 grid — BOTH loop counters place each window.",
    remix: "4×4: both ranges to 4, spacing to 65.",
    code: `color("darkslateblue")\nfor i in range(3):\n    for j in range(3):\n        penup()\n        jump(-80 + j * 80, -80 + i * 80)\n        dot(14)\n` },
  { id: "cb118", rank: "r", world: 3, emoji: "🖼️", title: "Frame in rotation",
    caption: "Two nested squares — the second turned 45. A classic tile heart.",
    remix: "Three frames, turning 30 each. The heart becomes a sun.",
    code: `color("goldenrod")\nwidth(3)\nfor i in range(2):\n    for j in range(4):\n        forward(110)\n        right(90)\n    right(45)\n` },
  { id: "cb119", rank: "b", world: 3, emoji: "🕌", title: "Ring of eight",
    caption: "Eight squares around a center — mosque-window geometry.",
    remix: "Widen the ring: forward(60) BEFORE each square (penup first!).",
    code: `color("darkcyan")\nwidth(2)\nfor i in range(8):\n    for j in range(4):\n        forward(75)\n        right(90)\n    right(45)\n` },

  /* ---- gentle-slope fillers (progression gate 2026-09-14): pure practice right after
     each concept is born — no steep cliffs (founder: "we go gentle") ---- */
  { id: "cb101", rank: "m", world: 1, emoji: "👣", title: "First steps",
    caption: "Just walking and one turn — the turtle's very first stroll.",
    remix: "Make the second walk longer than the first.",
    code: `forward(100)\nright(90)\nforward(100)\n` },
  { id: "cb102", rank: "m", world: 1, emoji: "⚡", title: "Zigzag path",
    caption: "Right, left, right — lightning made of walking.",
    remix: "Add two more zigs. Or make every zig longer.",
    code: `forward(60)\nright(90)\nforward(60)\nleft(90)\nforward(60)\nright(90)\nforward(60)\n` },
  { id: "cb103", rank: "m", world: 1, emoji: "🔁", title: "There and back",
    caption: "right(180) is a full about-face — walk out, walk home.",
    remix: "Come back only HALFWAY. Where does the turtle stop?",
    code: `forward(130)\nright(180)\nforward(65)\n` },
  { id: "cb104", rank: "m", world: 1, emoji: "🏺", title: "Jar of steps",
    caption: "One jar feeds three walks — change it once, all three obey.",
    remix: "step = 110. Watch all three lines grow together.",
    code: `step = 70\ncolor("teal")\nwidth(5)\nforward(step)\nright(90)\nforward(step)\nright(90)\nforward(step)\n` },
  { id: "cb105", rank: "b", world: 1, emoji: "🚪", title: "Doorway of two jars",
    caption: "tall and wide — two jars, one doorway.",
    remix: "A giant gate: tall = 160. A letterbox: tall = 30.",
    code: `tall = 120\nwide = 70\ncolor("saddlebrown")\nwidth(6)\nforward(tall)\nright(90)\nforward(wide)\nright(90)\nforward(tall)\n` },
];
